spring:
  h2:
    console.enabled: true
    console.path: /h2

  datasource.url: jdbc:h2:file:/home/guilherme/dbh2teste
  datasource.username: sa
  datasource.password:
  datasource.driver-class-name: org.h2.Driver

  jpa.hibernate.ddl-auto: create-drop


logging:
  level:
    br.com.st: DEBUG

